session "CPSVerification" = "Ordinary_Differential_Equations" +
  options [quick_and_dirty, document = pdf, document_output = "output"]
  sessions
    Ordinary_Differential_Equations
    Transformer_Semantics
    KAD
    Algebraic_VCs
  theories [document = false]
    "afpModified/Antidomain_Semiring"
    "afpModified/Dioid_Models"
    "afpModified/Domain_Semiring"
    "afpModified/KAT_Models"
    "afpModified/KAT"
    "afpModified/Kleene_Algebra_Models"
    "afpModified/Kleene_Algebra"
    "afpModified/Modal_Kleene_Algebra_Models"
    "afpModified/Modal_Kleene_Algebra"
    "afpModified/PHL_KA"
    "afpModified/PHL_KAT"
    "afpModified/Range_Semiring"
    "afpModified/VC_KAD"
    "afpModified/VC_KAT"
  theories
    "HybridVerifVecs/hs_prelims"
    "HybridVerifVecs/hs_prelims_dyn_sys"
    "HybridVerifVecs/hs_prelims_matrices"
    "HybridVerifVecs/hs_vc_spartan"
    "HybridVerifVecs/hs_vc_examples"
    "HybridVerifVecs/PredTransf/cat2funcset"
    "HybridVerifVecs/PredTransf/cat2funcset_examples"
    "HybridVerifVecs/MKA/mka2rel"
    "HybridVerifVecs/MKA/mka2ndfun"
    "HybridVerifVecs/MKA/mka_examples"
    "HybridVerifVecs/KAT/kat2rel"
    "HybridVerifVecs/KAT/kat2rel_examples"
    "HybridVerifLists/VC_diffKAD_auxiliarities"
    "HybridVerifLists/VC_diffKAD"
    "HybridVerifLists/VC_diffKAD_examples"
  document_files
    "root.tex"
